server:
  port: 8088

dubbo:
  application:
    name: cloudapp-microservice-dubbo-demo
  registry:
    address: nacos://127.0.0.1:8848
  metadata-report:
    address: nacos://127.0.0.1:8848
  config-center:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: com.alibaba.cloudapp.microservice.aliyun.demo

spring:
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  application:
    name: cloudapp-microservice-dubbo-demo

alicloud:
  deployment:
    mode: EDAS_MANAGED